### ISSUE TITLE
Breaking change in ripped:* tagging

### ISSUE THREAD

**Issue by yankovs** [CERT-Polska/karton-config-extractor#37]
Hey!

In previous versions of karton-reporter the parent was tagged as `ripped:<family>`, however right now it is tagged as `ripped: <family>` with a space. This means that (1) searching ripped tags will be affected and (2) samples that already have ripped:* tag can get two different tags like so:  
<img width="236" alt="image (2)" src="https://github.com/CERT-Polska/karton-config-extractor/assets/49753115/a44d1e3e-0eaf-4675-8f53-8578931d5ed9">

**Comment by nazywam** [comment]
Fixed, sorry about that!
